---

# General stuff

coda_orthanc_firewalld_zones:
  - zone: public
    state: enabled

coda_orthanc_group: orthanc
coda_orthanc_user: orthanc

coda_orthanc_image_repo: docker.io
coda_orthanc_image_name: osimis/orthanc
coda_orthanc_image_tag: 22.7.0

coda_orthanc_image_remote_check_hours: [ 0 ]
coda_orthanc_image_remote_check_runs:  [ 0 ]

# Systemd stuff

coda_orthanc_service_name: orthanc

coda_orthanc_systemd_temp_dir: "{{ '/tmp' if ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7 else '%T' }}"
coda_orthanc_systemd_timeout_start_sec: 120
coda_orthanc_systemd_restart_sec: 30

# Podman stuff

coda_orthanc_container_stop_timeout: 15
coda_orthanc_container_cidfile: "{{ coda_orthanc_systemd_temp_dir }}/%n-cid"
coda_orthanc_container_pidfile: "{{ coda_orthanc_systemd_temp_dir }}/%n-pid"
