---

- name: "IMPORT_TASKS | firewall.yml"
  import_tasks: firewall.yml
  tags:
    - coda_fhirbase
    - coda_fhirbase_firewall

- name: "IMPORT_TASKS | install.yml"
  import_tasks: install.yml
  tags:
    - coda_fhirbase
    - coda_fhirbase_install
