---
- name: "IMPORT_TASKS | firewall.yml"
  import_tasks: firewall.yml
  tags:
    - coda_green
    - coda_green_firewall

- name: "IMPORT_TASKS | cleanup-apis.yml"
  import_tasks: cleanup-apis.yml
  tags:
    - coda_green
    - coda_green_cleanup_apis

################################################################################
#### CODA-STATS-API
################################################################################

- when: _green_enable_stats_api | default(true)
  block:

    - name: "IMPORT_TASKS | CODA-STATS-API | install.yml"
      import_tasks: install.yml
      tags:
        - coda_green
        - coda_green_install
        - coda_green_stats_api
      vars:
        - task_title: CODA-STATS-API
        - container_name: coda-stats-api
        - container_port: "{{ coda_stats_api_port }}"
        - docker_image_name: "{{ coda_stats_api_image_name }}"
        - docker_image_tag: "{{ coda_stats_api_image_tag }}"

    # Start and enable service

    - name: CODA-STATS-API | SYSTEMD | Ensure coda-stats-api.service is started and enabled
      systemd:
        name: coda-stats-api
        state: started
        enabled: yes
        daemon_reload: yes
      # We register this task status.
      # Don't start + restart service with handlers, usualy on first run.
      register: _systemd_coda_stats_api
      tags:
        - coda_green
        - coda_green_install
        - coda_green_stats_api

    - meta: flush_handlers

################################################################################
#### CODA-LEARNING-API
################################################################################

- when: _green_enable_learning_api | default(true)
  block:

    - name: "IMPORT_TASKS | CODA-LEARNING-API | install.yml"
      import_tasks: install.yml
      tags:
        - coda_green
        - coda_green_install
        - coda_green_learning_api
      vars:
        - task_title: CODA-LEARNING-API
        - container_name: coda-learning-api
        - container_port: "{{ coda_learning_api_port }}"
        - docker_image_name: "{{ coda_learning_api_image_name }}"
        - docker_image_tag: "{{ coda_learning_api_image_tag }}"

    # Start and enable service
    - name: CODA-LEARNING-API | SYSTEMD | Ensure coda19-learning-api.service is started and enabled
      systemd:
        name: coda-learning-api
        state: started
        enabled: yes
        daemon_reload: yes
      # We register this task status.
      # Don't start + restart service with handlers, usualy on first run.
      register: _systemd_coda_learning_api
      tags:
        - coda_green
        - coda_green_install
        - coda_green_learning_api

    - meta: flush_handlers

################################################################################
#### CODA-SITE-API
################################################################################
# Never deploy the site API in a sandbox. The service would register in our hub (useless)
- when: (coda_site_id | int != 999) and (_green_enable_site_api | default(true))
  block:

    - name: "IMPORT_TASKS | CODA-SITE-API | install.yml"
      import_tasks: install.yml
      tags:
        - coda_green
        - coda_green_install
        - coda_green_site_api
      vars:
        - task_title: CODA-SITE-API
        - container_name: coda-site-api
        - container_port: "{{ coda_site_api_port }}"
        - docker_image_name: "{{ coda_site_api_image_name }}"
        - docker_image_tag: "{{ coda_site_api_image_tag }}"

    # Start and enable service
    - name: CODA-SITE-API | SYSTEMD | Ensure coda-site-api.service is started and enabled
      systemd:
        name: coda-site-api
        state: started
        enabled: yes
        daemon_reload: yes
      # We register this task status.
      # Don't start + restart service with handlers, usualy on first run.
      register: _systemd_coda_site_api
      tags:
        - coda_green
        - coda_green_install
        - coda_green_site_api

    - meta: flush_handlers
